### ISSUE TITLE
Bad SMTP port for smtp4dev [FR]

### ISSUE THREAD

**Issue by FYHenry** [atsuhikoMochizuki/Inote_backup#1]
# Bad SMTP port for *smtp4dev* [1]

## Problème

Le port SMTP est bien `24` en temps normal mais les 1024 premiers ports UDP/TCP sont protégés par le système GNU/Linux. Seul une application système peut s’en servir et passer par la commande `sudo` est une véritable hérésie!

À la limite si un démon `smtp4devd` existe ça peut devenir pertinent.

## Solution

Pour rester un utilisateur lors des essais du serveur dorsal, un nouveau port SMTP peut être configuré dans `${XDG_CONFIG_HOME}/appsettings.json` ou `smtp-dev/appsettings.json` :

```json
{
  "ServerOptions": {
    "Port": 2525
  }
}
```

Un paramètre doit aussi être ajusté dans les propriétés du fichier `src/test/resources/application-test.properties` du serveur dorsal :

```properties
# default protocol port + 3000 as offset
spring.mail.port=2525
```

## Extra

Le fichier `smtpServer_simul_run.sh` devient inutile.

[1] https://github.com/rnwood/smtp4dev

**Comment by atsuhikoMochizuki** [comment]
Smtp4dev est émulateur de serveur SMTP que j'utilise ponctuellement lorsque je teste manuellement l'API, lorsqu'elle doit envoyer un mail suite à une requête (par exemple lors de l'inscription pour l'envoi du code d'activation). Il redirige les email sortants vers la machine hôte, et on peut les lire sur une boite de réception fictive dans un navigateur sur le port 5000. 
Ce programme nécessite donc des privilèges élevés pour accéder au réseau et au système de fichier d'où l'utilisation du sudo.
D'ailleurs si tu le lance sur le port 2525 il affiche aussi permission denied.
A vrai dire je ne m'était pas posé la question et merci pour la pertinence de ta remarque @FYHenry car je crois que le serveur tourne sur le port 25 et il faudra que je le corrige.

**Comment by atsuhikoMochizuki** [comment]
Ca existe et je l'utilise pour le test unitaire: GreenMail
